apiVersion: 1

datasources:
  - name: analytics-db
    uid: analyticsdb
    type: postgres
    access: proxy
    url: $__env{ANALYTICS_DB_HOST}:$__env{ANALYTICS_DB_PORT}
    database: $__env{ANALYTICS_DB_NAME}
    user: $__env{ANALYTICS_DB_USER}
    secureJsonData:
      password: $__env{ANALYTICS_DB_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: false
