spring:
  application:
    name: flight-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

server:
  port: ${SERVER_PORT}